services:
  db:
    image: mariadb:11.4
    container_name: moodle_db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      MARIADB_ROOT_PASSWORD: moodle_root_pwd
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle_user
      MARIADB_PASSWORD: moodle_pwd
      MYSQL_ROOT_PASSWORD: moodle_root_pwd
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_pwd
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      MOODLE_DBTYPE: mariadb
      MOODLE_DBHOST: db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle_user
      MOODLE_DBPASS: moodle_pwd
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin_pwd
      MOODLE_SITENAME: "TIC - Centuria"
      # - APACHE_DOCUMENT_ROOT: /var/www/html/public
    volumes:
      - ./moodle:/var/www/html
      - moodledata_data:/var/www/moodledata
      - ./moodle/public/local/marcado:/var/www/html/public/local/marcado

volumes:
  db_data:
  moodledata_data:
