# -*- coding: utf-8 -*-

def update_christhian():
    with open('generate_final_clean.py', 'r', encoding='utf-8') as f:
        content = f.read()

    old_planteamiento = '''        ("PLANTEAMIENTO DEL PROBLEMA", 1, """El ecosistema de recaudación de la Municipalidad de Asunción presenta una sintomatología preocupante en cuanto a la sincronización de sus datos fiscales. El principal inconveniente detectado es la desconexión existente entre la base de datos del Departamento de Catastro y el sistema central de contabilidad y tesorería. Esta falta de interoperabilidad genera discrepancias sustanciales entre los montos emitidos en concepto de Impuesto Inmobiliario y los saldos efectivamente percibidos.

Los medios de comunicación locales han denunciado en reiteradas ocasiones las deficiencias en este ámbito, destacando casos donde los contribuyentes sufren la duplicación de sus obligaciones tributarias debido a registros desfasados. Este caos administrativo no solo afecta al ciudadano, sino que impide que la institución tenga una lectura real de su cartera de deudores, ocultando cifras millonarias de morosidad que, en muchos casos, terminan prescribiendo sin gestión de cobro alguna.

Adicionalmente, se ha observado un intento por parte de las autoridades de aplicar medidas coercitivas, tales como convenios con empresas calificadoras de riesgo crediticio para incluir a los deudores en listas negras. Sin embargo, estas iniciativas han encontrado resistencia por la baja confiabilidad de los datos base. En este contexto, surge la necesidad de formular la siguiente interrogante principal: ¿De qué manera la falta de integración entre el catastro y la contabilidad pública afecta la gestión del Impuesto Inmobiliario en la Municipalidad de Asunción?

Para dar respuesta a esta interrogante, se plantean los siguientes objetivos específicos: 1) Describir el flujo actual de la información catastral hacia los estados financieros. 2) Identificar las debilidades normativas y procedimentales que facilitan la morosidad. 3) Proponer lineamientos para un modelo de integración tecnológica que garantice la precisión y oportunidad de la información contable."""),'''

    new_planteamiento = '''        ("CAPÍTULO 1. PLANTEAMIENTO DEL PROBLEMA", 1, ""),
        ("1.1. Contexto y Descripción del Problema", 2, """El ecosistema de recaudación de la Municipalidad de Asunción presenta una sintomatología preocupante en cuanto a la sincronización de sus datos fiscales. El principal inconveniente detectado es la desconexión existente entre la base de datos del Departamento de Catastro y el sistema central de contabilidad y tesorería. Esta falta de interoperabilidad genera discrepancias sustanciales entre los montos emitidos en concepto de Impuesto Inmobiliario y los saldos efectivamente percibidos.

Los medios de comunicación locales han denunciado en reiteradas ocasiones las deficiencias en este ámbito, destacando casos donde los contribuyentes sufren la duplicación de sus obligaciones tributarias debido a registros desfasados. Este caos administrativo no solo afecta al ciudadano, sino que impide que la institución tenga una lectura real de su cartera de deudores, ocultando cifras millonarias de morosidad que, en muchos casos, terminan prescribiendo sin gestión de cobro alguna."""),
        ("1.2. Pregunta de Investigación", 2, """Adicionalmente, se ha observado un intento por parte de las autoridades de aplicar medidas coercitivas, tales como convenios con empresas calificadoras de riesgo crediticio para incluir a los deudores en listas negras. Sin embargo, estas iniciativas han encontrado resistencia por la baja confiabilidad de los datos base. En este contexto, surge la necesidad de formular la siguiente interrogante principal: ¿De qué manera la falta de integración entre el catastro y la contabilidad pública afecta la gestión del Impuesto Inmobiliario en la Municipalidad de Asunción?"""),
        ("1.3. Objetivos Específicos", 2, """Para dar respuesta a esta interrogante, se plantean los siguientes objetivos específicos: 1) Describir el flujo actual de la información catastral hacia los estados financieros. 2) Identificar las debilidades normativas y procedimentales que facilitan la morosidad. 3) Proponer lineamientos para un modelo de integración tecnológica que garantice la precisión y oportunidad de la información contable."""),'''

    content = content.replace(old_planteamiento, new_planteamiento)
    with open('generate_final_clean.py', 'w', encoding='utf-8') as f:
        f.write(content)

def update_nelly():
    with open('generate_nelly_clean.py', 'r', encoding='utf-8') as f:
        content = f.read()

    old_planteamiento = '''        ("PLANTEAMIENTO DEL PROBLEMA", 1, "El sistema de contrataciones del Estado y la ejecución del presupuesto enfrentan una crisis de eficiencia caracterizada por el incumplimiento crónico de los cronogramas de adquisiciones. Las instituciones públicas a menudo llegan al último trimestre del año fiscal con niveles de ejecución alarmantemente bajos, lo que desencadena una carrera apresurada por gastar los saldos disponibles. Esta ejecución forzada de última hora compromete la calidad de los bienes y servicios adquiridos y vulnera los principios de economía y eficiencia establecidos en la legislación vigente.\\n\\nUno de los nudos críticos identificados es la falta de trazabilidad y las demoras injustificadas en las diferentes etapas del proceso de contratación, especialmente en la evaluación de ofertas y la justificación de adendas. Las observaciones periódicas realizadas por la Dirección Nacional de Contrataciones Públicas (DNCP) y la Contraloría General de la República reflejan una recurrente falta de planificación anual. Los requerimientos nacen desconectados de los planes operativos, y los pliegos de bases y condiciones suelen elaborarse con falencias técnicas que derivan en protestas, anulaciones y el consecuente reinicio del ciclo burocrático.\\n\\nAdicionalmente, se observa una implementación deficiente del Modelo Estándar de Control Interno para Instituciones Públicas (MECIP). En lugar de funcionar como una herramienta de gestión preventiva y mitigación de riesgos, el MECIP a menudo se aborda como un simple requisito documental para cumplir con las auditorías, perdiendo su verdadera utilidad. Esta desconexión entre el control interno y las operaciones diarias de la Unidad Operativa de Contrataciones (UOC) genera un ambiente propicio para la opacidad y la discrecionalidad administrativa.\\n\\nFrente a este escenario, se formula la siguiente pregunta central de investigación: ¿Cuáles son las deficiencias procedimentales y de control interno que generan demoras y falta de transparencia en la ejecución presupuestaria y los procesos de compras públicas? Para abordar este cuestionamiento, los objetivos específicos se orientan a evaluar el cumplimiento de los tiempos normativos en las licitaciones, analizar la eficacia de los controles preventivos actuales y proponer lineamientos para la estandarización y digitalización de los procesos de adquisición."),'''

    new_planteamiento = '''        ("CAPÍTULO 1. PLANTEAMIENTO DEL PROBLEMA", 1, ""),
        ("1.1. Contexto y Descripción del Problema", 2, "El sistema de contrataciones del Estado y la ejecución del presupuesto enfrentan una crisis de eficiencia caracterizada por el incumplimiento crónico de los cronogramas de adquisiciones. Las instituciones públicas a menudo llegan al último trimestre del año fiscal con niveles de ejecución alarmantemente bajos, lo que desencadena una carrera apresurada por gastar los saldos disponibles. Esta ejecución forzada de última hora compromete la calidad de los bienes y servicios adquiridos y vulnera los principios de economía y eficiencia establecidos en la legislación vigente.\\n\\nUno de los nudos críticos identificados es la falta de trazabilidad y las demoras injustificadas en las diferentes etapas del proceso de contratación, especialmente en la evaluación de ofertas y la justificación de adendas. Las observaciones periódicas realizadas por la Dirección Nacional de Contrataciones Públicas (DNCP) y la Contraloría General de la República reflejan una recurrente falta de planificación anual. Los requerimientos nacen desconectados de los planes operativos, y los pliegos de bases y condiciones suelen elaborarse con falencias técnicas que derivan en protestas, anulaciones y el consecuente reinicio del ciclo burocrático."),
        ("1.2. Deficiencias de Control Interno", 2, "Adicionalmente, se observa una implementación deficiente del Modelo Estándar de Control Interno para Instituciones Públicas (MECIP). En lugar de funcionar como una herramienta de gestión preventiva y mitigación de riesgos, el MECIP a menudo se aborda como un simple requisito documental para cumplir con las auditorías, perdiendo su verdadera utilidad. Esta desconexión entre el control interno y las operaciones diarias de la Unidad Operativa de Contrataciones (UOC) genera un ambiente propicio para la opacidad y la discrecionalidad administrativa."),
        ("1.3. Pregunta y Objetivos de Investigación", 2, "Frente a este escenario, se formula la siguiente pregunta central de investigación: ¿Cuáles son las deficiencias procedimentales y de control interno que generan demoras y falta de transparencia en la ejecución presupuestaria y los procesos de compras públicas? Para abordar este cuestionamiento, los objetivos específicos se orientan a evaluar el cumplimiento de los tiempos normativos en las licitaciones, analizar la eficacia de los controles preventivos actuales y proponer lineamientos para la estandarización y digitalización de los procesos de adquisición."),'''

    content = content.replace(old_planteamiento, new_planteamiento)
    with open('generate_nelly_clean.py', 'w', encoding='utf-8') as f:
        f.write(content)

update_christhian()
update_nelly()
