# -*- coding: utf-8 -*-

def update_nelly():
    with open('generate_nelly_clean.py', 'r', encoding='utf-8') as f:
        content = f.read()

    old_cap2 = '''        ("CAPÍTULO 2. MARCO TEÓRICO Y NORMATIVO", 1, "El presupuesto público no es simplemente un documento contable; es la expresión financiera de las prioridades del gobierno. Desde la perspectiva de la gestión pública moderna, la ejecución presupuestaria debe regirse por los principios de legalidad, eficiencia, eficacia y economía. La literatura académica resalta que el ciclo presupuestario comprende varias etapas interdependientes: programación, formulación, aprobación, ejecución y evaluación. Cualquier ruptura o retraso en la etapa de ejecución, particularmente en el componente de compras, invalida el esfuerzo de planificación previo.\\n\\nEn la República del Paraguay, la Ley N° 2051/03 \\"De Contrataciones Públicas\\" y sus decretos reglamentarios establecen el marco rector para las adquisiciones del Estado. Esta legislación introdujo un cambio de paradigma al crear el Sistema de Información de las Contrataciones Públicas (SICP), obligando a las entidades a transparentar sus procesos mediante la publicación en línea de sus llamados. No obstante, la transparencia pasiva (publicar documentos) no garantiza la eficiencia activa (comprar rápido y bien). La ley promueve el trato igualitario y la libre competencia, pero su aplicación práctica a menudo se ve entorpecida por interpretaciones excesivamente legalistas o por el desconocimiento técnico de los comités de evaluación.\\n\\nComplementariamente, el control interno se erige como el mecanismo de aseguramiento de la integridad administrativa. La adopción del Modelo Estándar de Control Interno para Instituciones Públicas del Paraguay (MECIP), impulsado por la Contraloría General de la República, busca proporcionar una estructura uniforme para que las entidades evalúen y mejoren sus operaciones. El MECIP fundamenta el autocontrol, la autorregulación y la autogestión. En el contexto de las compras públicas, un control interno robusto debería identificar y mitigar riesgos como el fraccionamiento de contratos, el direccionamiento de pliegos y los sobrecostos.\\n\\nLa doctrina contemporánea sobre transparencia gubernamental introduce el concepto de \\"Gobierno Abierto\\" (Open Government), el cual aboga por el uso de tecnologías de la información para promover la rendición de cuentas. La apertura de datos (Open Data) en las contrataciones permite a la sociedad civil y a los medios de comunicación auditar el gasto público en tiempo real. Sin embargo, para que esta auditoría social sea efectiva, los datos deben ser de alta calidad, estructurados y oportunos. La transición hacia un modelo de compras públicas electrónicas integrales es, según los estándares internacionales del Banco Interamericano de Desarrollo (BID), el paso definitivo para erradicar las ineficiencias procedimentales detalladas en este marco."),'''

    new_cap2 = '''        ("CAPÍTULO 2. MARCO TEÓRICO Y NORMATIVO", 1, ""),
        ("2.1. El Ciclo Presupuestario y su Importancia", 2, "El presupuesto público no es simplemente un documento contable; es la expresión financiera de las prioridades del gobierno. Desde la perspectiva de la gestión pública moderna, la ejecución presupuestaria debe regirse por los principios de legalidad, eficiencia, eficacia y economía. La literatura académica resalta que el ciclo presupuestario comprende varias etapas interdependientes: programación, formulación, aprobación, ejecución y evaluación. Cualquier ruptura o retraso en la etapa de ejecución, particularmente en el componente de compras, invalida el esfuerzo de planificación previo."),
        ("2.2. La Ley N° 2051/03 y la Transparencia Pasiva", 2, "En la República del Paraguay, la Ley N° 2051/03 \\"De Contrataciones Públicas\\" y sus decretos reglamentarios establecen el marco rector para las adquisiciones del Estado. Esta legislación introdujo un cambio de paradigma al crear el Sistema de Información de las Contrataciones Públicas (SICP), obligando a las entidades a transparentar sus procesos mediante la publicación en línea de sus llamados. No obstante, la transparencia pasiva (publicar documentos) no garantiza la eficiencia activa (comprar rápido y bien). La ley promueve el trato igualitario y la libre competencia, pero su aplicación práctica a menudo se ve entorpecida por interpretaciones excesivamente legalistas o por el desconocimiento técnico de los comités de evaluación."),
        ("2.3. El Control Interno (MECIP) como Mecanismo de Integridad", 2, "Complementariamente, el control interno se erige como el mecanismo de aseguramiento de la integridad administrativa. La adopción del Modelo Estándar de Control Interno para Instituciones Públicas del Paraguay (MECIP), impulsado por la Contraloría General de la República, busca proporcionar una estructura uniforme para que las entidades evalúen y mejoren sus operaciones. El MECIP fundamenta el autocontrol, la autorregulación y la autogestión. En el contexto de las compras públicas, un control interno robusto debería identificar y mitigar riesgos como el fraccionamiento de contratos, el direccionamiento de pliegos y los sobrecostos."),
        ("2.4. Gobierno Abierto y Compras Públicas Electrónicas", 2, "La doctrina contemporánea sobre transparencia gubernamental introduce el concepto de \\"Gobierno Abierto\\" (Open Government), el cual aboga por el uso de tecnologías de la información para promover la rendición de cuentas. La apertura de datos (Open Data) en las contrataciones permite a la sociedad civil y a los medios de comunicación auditar el gasto público en tiempo real. Sin embargo, para que esta auditoría social sea efectiva, los datos deben ser de alta calidad, estructurados y oportunos. La transición hacia un modelo de compras públicas electrónicas integrales es, según los estándares internacionales del Banco Interamericano de Desarrollo (BID), el paso definitivo para erradicar las ineficiencias procedimentales detalladas en este marco."),'''

    content = content.replace(old_cap2, new_cap2)

    old_cap3 = '''        ("CAPÍTULO 3. METODOLOGÍA", 1, "El diseño metodológico aplicado a esta investigación es de naturaleza cualitativa, descriptiva y no experimental. El enfoque cualitativo permite explorar las complejidades del comportamiento organizacional y los procesos administrativos dentro de las Unidades Operativas de Contrataciones (UOC). Se clasifica como descriptivo ya que tiene como fin especificar las propiedades, características y los perfiles de los procedimientos burocráticos que intervienen en la ejecución presupuestaria, sin intención de manipular variables o establecer correlaciones estadísticas causales absolutas.\\n\\nEl método principal de recolección de datos fue la revisión documental y el análisis de contenido. Se examinaron reportes de ejecución presupuestaria, informes de auditoría del MECIP, resoluciones de la Dirección Nacional de Contrataciones Públicas (DNCP) respecto a protestas y anulaciones, y manuales de funciones internos. Esta documentación fue triangulada para identificar patrones recurrentes de retrasos y fallas de control.\\n\\nAdicionalmente, se incorporaron técnicas de observación indirecta de los portales de transparencia y del Sistema de Información de las Contrataciones Públicas (SICP), evaluando la disponibilidad, oportunidad y completitud de la documentación respaldatoria que las entidades están obligadas a publicar. El análisis de los datos se realizó mediante la codificación de las deficiencias encontradas en tres categorías principales: fallas de planificación, cuellos de botella procedimentales y debilidades del control interno."),'''

    new_cap3 = '''        ("CAPÍTULO 3. METODOLOGÍA", 1, ""),
        ("3.1. Enfoque y Tipo de Investigación", 2, "El diseño metodológico aplicado a esta investigación es de naturaleza cualitativa, descriptiva y no experimental. El enfoque cualitativo permite explorar las complejidades del comportamiento organizacional y los procesos administrativos dentro de las Unidades Operativas de Contrataciones (UOC). Se clasifica como descriptivo ya que tiene como fin especificar las propiedades, características y los perfiles de los procedimientos burocráticos que intervienen en la ejecución presupuestaria, sin intención de manipular variables o establecer correlaciones estadísticas causales absolutas."),
        ("3.2. Técnicas de Recolección de Datos", 2, "El método principal de recolección de datos fue la revisión documental y el análisis de contenido. Se examinaron reportes de ejecución presupuestaria, informes de auditoría del MECIP, resoluciones de la Dirección Nacional de Contrataciones Públicas (DNCP) respecto a protestas y anulaciones, y manuales de funciones internos. Esta documentación fue triangulada para identificar patrones recurrentes de retrasos y fallas de control."),
        ("3.3. Observación Indirecta y Categorías de Análisis", 2, "Adicionalmente, se incorporaron técnicas de observación indirecta de los portales de transparencia y del Sistema de Información de las Contrataciones Públicas (SICP), evaluando la disponibilidad, oportunidad y completitud de la documentación respaldatoria que las entidades están obligadas a publicar. El análisis de los datos se realizó mediante la codificación de las deficiencias encontradas en tres categorías principales: fallas de planificación, cuellos de botella procedimentales y debilidades del control interno."),'''

    content = content.replace(old_cap3, new_cap3)

    old_cap4 = '''        ("CAPÍTULO 4. RESULTADOS", 1, "El análisis documental reveló que una de las causas primarias de la baja ejecución presupuestaria radica en la deficiente formulación del Plan Anual de Contrataciones (PAC). Se constató que, en promedio, más del 40% de los llamados a licitación programados sufren modificaciones sustanciales o son cancelados debido a que los requerimientos técnicos elaborados por las áreas solicitantes son imprecisos o no se ajustan a las realidades del mercado. Esta falta de rigor en el origen del pedido paraliza el expediente administrativo durante semanas en la etapa de pre-inversión.\\n\\nEn cuanto a los tiempos procedimentales, se detectó que la etapa de evaluación de ofertas es el mayor cuello de botella. Mientras la normativa sugiere plazos razonables para emitir dictámenes, los Comités de Evaluación exceden regularmente estos tiempos, acumulando demoras que superan los 45 a 60 días desde la apertura de sobres hasta la recomendación de adjudicación. Estas demoras se justifican frecuentemente por la falta de quorum de los miembros del comité, la sobrecarga laboral y la excesiva dependencia de consultas aclaratorias a los oferentes debido a ambigüedades en los pliegos iniciales.\\n\\nRespecto al control interno y la transparencia, los resultados indican que la implementación del MECIP se percibe más como una carga burocrática orientada al cumplimiento formal de formatos que como una herramienta gerencial. Los mapas de riesgos del área de adquisiciones rara vez se actualizan proactivamente y los controles aplicados son detectivos (una vez cometido el error) en lugar de preventivos. Asimismo, aunque la información se publica en los portales gubernamentales, se evidenció que los documentos respaldatorios de pagos (facturas, actas de recepción) se cargan con retraso, dificultando la trazabilidad del gasto en tiempo real por parte de la ciudadanía y los órganos de control."),'''

    new_cap4 = '''        ("CAPÍTULO 4. RESULTADOS", 1, ""),
        ("4.1. Deficiencias en el Plan Anual de Contrataciones", 2, "El análisis documental reveló que una de las causas primarias de la baja ejecución presupuestaria radica en la deficiente formulación del Plan Anual de Contrataciones (PAC). Se constató que, en promedio, más del 40% de los llamados a licitación programados sufren modificaciones sustanciales o son cancelados debido a que los requerimientos técnicos elaborados por las áreas solicitantes son imprecisos o no se ajustan a las realidades del mercado. Esta falta de rigor en el origen del pedido paraliza el expediente administrativo durante semanas en la etapa de pre-inversión."),
        ("4.2. Retrasos en la Evaluación de Ofertas", 2, "En cuanto a los tiempos procedimentales, se detectó que la etapa de evaluación de ofertas es el mayor cuello de botella. Mientras la normativa sugiere plazos razonables para emitir dictámenes, los Comités de Evaluación exceden regularmente estos tiempos, acumulando demoras que superan los 45 a 60 días desde la apertura de sobres hasta la recomendación de adjudicación. Estas demoras se justifican frecuentemente por la falta de quorum de los miembros del comité, la sobrecarga laboral y la excesiva dependencia de consultas aclaratorias a los oferentes debido a ambigüedades en los pliegos iniciales."),
        ("4.3. Implementación Burocrática del MECIP", 2, "Respecto al control interno y la transparencia, los resultados indican que la implementación del MECIP se percibe más como una carga burocrática orientada al cumplimiento formal de formatos que como una herramienta gerencial. Los mapas de riesgos del área de adquisiciones rara vez se actualizan proactivamente y los controles aplicados son detectivos (una vez cometido el error) en lugar de preventivos. Asimismo, aunque la información se publica en los portales gubernamentales, se evidenció que los documentos respaldatorios de pagos (facturas, actas de recepción) se cargan con retraso, dificultando la trazabilidad del gasto en tiempo real por parte de la ciudadanía y los órganos de control."),'''

    content = content.replace(old_cap4, new_cap4)

    old_cap5 = '''        ("CAPÍTULO 5. ANÁLISIS Y DIAGNÓSTICO", 1, "La interpretación de los resultados pone de manifiesto una cultura organizacional reactiva y resistente al cambio dentro de la gestión de compras públicas. La ineficiencia en la ejecución del presupuesto no es producto de un marco legal deficiente; por el contrario, la Ley 2051/03 provee las herramientas necesarias para adquisiciones ágiles. El problema central es la debilidad institucional en la fase de planificación y la falta de profesionalización continua del personal involucrado en las áreas solicitantes y en la UOC.\\n\\nEl diagnóstico señala que existe un \\"efecto embudo\\" administrativo provocado por la excesiva centralización de las firmas y aprobaciones, sumado a la falta de sistemas integrados de gestión documental (ERP). Gran parte del retraso documentado obedece a que los expedientes aún transitan físicamente por múltiples dependencias, requiriendo visaciones redundantes que no agregan valor de control, sino que simplemente diluyen la responsabilidad. Esta burocratización extrema es contraproducente para la transparencia, ya que en la maraña de firmas resulta difícil identificar dónde y por qué se estanca un proceso.\\n\\nDesde la óptica del MECIP, el diagnóstico es crítico: el sistema inmunológico de la institución contra la ineficiencia y la corrupción está desactivado por la rutina. Sin controles automatizados e integrados en el flujo de trabajo (workflow) informático, la entidad depende exclusivamente de la revisión manual y del criterio subjetivo de los funcionarios, aumentando exponencialmente el margen de error y las oportunidades para prácticas de favoritismo."),'''

    new_cap5 = '''        ("CAPÍTULO 5. ANÁLISIS Y DIAGNÓSTICO", 1, ""),
        ("5.1. Cultura Organizacional Resistente al Cambio", 2, "La interpretación de los resultados pone de manifiesto una cultura organizacional reactiva y resistente al cambio dentro de la gestión de compras públicas. La ineficiencia en la ejecución del presupuesto no es producto de un marco legal deficiente; por el contrario, la Ley 2051/03 provee las herramientas necesarias para adquisiciones ágiles. El problema central es la debilidad institucional en la fase de planificación y la falta de profesionalización continua del personal involucrado en las áreas solicitantes y en la UOC."),
        ("5.2. El Efecto Embudo y la Burocratización", 2, "El diagnóstico señala que existe un \\"efecto embudo\\" administrativo provocado por la excesiva centralización de las firmas y aprobaciones, sumado a la falta de sistemas integrados de gestión documental (ERP). Gran parte del retraso documentado obedece a que los expedientes aún transitan físicamente por múltiples dependencias, requiriendo visaciones redundantes que no agregan valor de control, sino que simplemente diluyen la responsabilidad. Esta burocratización extrema es contraproducente para la transparencia, ya que en la maraña de firmas resulta difícil identificar dónde y por qué se estanca un proceso."),
        ("5.3. Desactivación del Control Preventivo", 2, "Desde la óptica del MECIP, el diagnóstico es crítico: el sistema inmunológico de la institución contra la ineficiencia y la corrupción está desactivado por la rutina. Sin controles automatizados e integrados en el flujo de trabajo (workflow) informático, la entidad depende exclusivamente de la revisión manual y del criterio subjetivo de los funcionarios, aumentando exponencialmente el margen de error y las oportunidades para prácticas de favoritismo."),'''

    content = content.replace(old_cap5, new_cap5)

    old_cap6 = '''        ("CAPÍTULO 6. PROPUESTAS Y RECOMENDACIONES", 1, "Para revertir las deficiencias diagnosticadas y asegurar una ejecución presupuestaria eficiente y transparente, se formulan las siguientes recomendaciones estratégicas:\\n\\n1. Capacitación y Profesionalización del Área Solicitante: Implementar programas de formación obligatoria para los funcionarios encargados de redactar las especificaciones técnicas, enfocándose en estudios de mercado y en la alineación estricta de las compras con el Plan Operativo Anual (POA).\\n\\n2. Digitalización y Cero Papel: Acelerar la transición hacia la gestión documental electrónica y el uso de firmas digitales en todo el ciclo de compras. Eliminar el tránsito físico de expedientes mediante un sistema de workflow que asigne tiempos máximos de retención en cada departamento, generando alertas automáticas ante retrasos injustificados.\\n\\n3. Reingeniería del Control Interno (MECIP): Integrar los controles preventivos directamente en el software de gestión (controles de sistema) para impedir, por ejemplo, el avance de un pedido sin disponibilidad presupuestaria verificada, minimizando la intervención manual y revitalizando el enfoque del MECIP hacia la prevención de riesgos operativos.\\n\\n4. Creación de Manuales de Procedimientos Estandarizados: Diseñar flujogramas simplificados y manuales de roles y funciones claros para los Comités de Evaluación, estableciendo indicadores de desempeño (KPIs) relacionados con los tiempos de adjudicación para medir objetivamente la eficiencia del proceso."),'''

    new_cap6 = '''        ("CAPÍTULO 6. PROPUESTAS Y RECOMENDACIONES", 1, "Para revertir las deficiencias diagnosticadas y asegurar una ejecución presupuestaria eficiente y transparente, se formulan las siguientes recomendaciones estratégicas:"),
        ("6.1. Profesionalización del Área Solicitante", 2, "1. Capacitación y Profesionalización del Área Solicitante: Implementar programas de formación obligatoria para los funcionarios encargados de redactar las especificaciones técnicas, enfocándose en estudios de mercado y en la alineación estricta de las compras con el Plan Operativo Anual (POA)."),
        ("6.2. Digitalización de Trámites", 2, "2. Digitalización y Cero Papel: Acelerar la transición hacia la gestión documental electrónica y el uso de firmas digitales en todo el ciclo de compras. Eliminar el tránsito físico de expedientes mediante un sistema de workflow que asigne tiempos máximos de retención en cada departamento, generando alertas automáticas ante retrasos injustificados."),
        ("6.3. Reingeniería del MECIP", 2, "3. Reingeniería del Control Interno (MECIP): Integrar los controles preventivos directamente en el software de gestión (controles de sistema) para impedir, por ejemplo, el avance de un pedido sin disponibilidad presupuestaria verificada, minimizando la intervención manual y revitalizando el enfoque del MECIP hacia la prevención de riesgos operativos."),
        ("6.4. Manuales Estandarizados y KPIs", 2, "4. Creación de Manuales de Procedimientos Estandarizados: Diseñar flujogramas simplificados y manuales de roles y funciones claros para los Comités de Evaluación, estableciendo indicadores de desempeño (KPIs) relacionados con los tiempos de adjudicación para medir objetivamente la eficiencia del proceso."),'''

    content = content.replace(old_cap6, new_cap6)

    with open('generate_nelly_clean.py', 'w', encoding='utf-8') as f:
        f.write(content)

update_nelly()
