# -*- coding: utf-8 -*-

def update_christhian():
    with open('generate_final_clean.py', 'r', encoding='utf-8') as f:
        content = f.read()

    old_cap2 = '''        ("CAPÍTULO 2. MARCO TEÓRICO Y NORMATIVO", 1, """La contabilidad pública constituye el sistema de información integral de las entidades del Estado. Su función principal es registrar y presentar de forma estructurada los eventos económicos que afectan el patrimonio gubernamental. A diferencia de la contabilidad privada, cuyo objetivo es medir la rentabilidad, la contabilidad gubernamental busca garantizar la rendición de cuentas (accountability) y la transparencia en la gestión de los recursos de la sociedad.

En el contexto internacional, las Normas Internacionales de Contabilidad del Sector Público (NICSP), emitidas por la Federación Internacional de Contadores (IFAC), establecen los parámetros para la presentación de los estados financieros. Un pilar fundamental de estas normas es el principio del devengado, el cual exige que las transacciones sean reconocidas cuando ocurren, independientemente de cuándo se produzca el flujo de efectivo. Para la recaudación del Impuesto Inmobiliario, esto implica que el municipio debe reconocer un activo (cuenta por cobrar) y un ingreso en el momento en que se emite la liquidación del impuesto, y no solo cuando el contribuyente realiza el pago.

Sin embargo, para aplicar correctamente el devengado, es imprescindible contar con una base de datos catastral íntegra y precisa. El Catastro se define como el inventario o censo, debidamente actualizado y clasificado, de los bienes inmuebles pertenecientes al Estado y a los particulares. Este inventario tiene un propósito múltiple: físico (identificar los límites territoriales), jurídico (vincular el inmueble con su propietario) y económico (establecer el valor fiscal base para la tributación).

En Paraguay, la Ley N° 3966/10 "Orgánica Municipal" otorga a las intendencias la autonomía política, administrativa y normativa para la gestión de sus intereses. El Artículo 169 de dicha ley establece que el Impuesto Inmobiliario es de competencia exclusiva de los municipios. No obstante, la legislación también obliga a las comunas a transferir el 15% de lo recaudado a las Gobernaciones Departamentales y otro 15% al Ministerio de Hacienda. Por tanto, una liquidación inexacta por fallas en el catastro no solo perjudica las arcas de Asunción, sino que constituye un incumplimiento de las obligaciones de transferencia a nivel nacional.

Autores contemporáneos en gestión pública coinciden en que la modernización de los sistemas catastrales es la inversión con mayor tasa de retorno para un municipio. Un catastro digitalizado, integrado con sistemas de información geográfica (SIG) y conectado en tiempo real con el módulo de tesorería, elimina la posibilidad de evasión fiscal por manipulación manual de datos. La doctrina sostiene que la descentralización fiscal, para ser efectiva, requiere instituciones locales con capacidad tecnológica para administrar bases de datos masivas."""),'''
    
    new_cap2 = '''        ("CAPÍTULO 2. MARCO TEÓRICO Y NORMATIVO", 1, ""),
        ("2.1. Contabilidad Pública y Transparencia", 2, """La contabilidad pública constituye el sistema de información integral de las entidades del Estado. Su función principal es registrar y presentar de forma estructurada los eventos económicos que afectan el patrimonio gubernamental. A diferencia de la contabilidad privada, cuyo objetivo es medir la rentabilidad, la contabilidad gubernamental busca garantizar la rendición de cuentas (accountability) y la transparencia en la gestión de los recursos de la sociedad."""),
        ("2.2. Normas Internacionales de Contabilidad del Sector Público (NICSP)", 2, """En el contexto internacional, las Normas Internacionales de Contabilidad del Sector Público (NICSP), emitidas por la Federación Internacional de Contadores (IFAC), establecen los parámetros para la presentación de los estados financieros. Un pilar fundamental de estas normas es el principio del devengado, el cual exige que las transacciones sean reconocidas cuando ocurren, independientemente de cuándo se produzca el flujo de efectivo. Para la recaudación del Impuesto Inmobiliario, esto implica que el municipio debe reconocer un activo (cuenta por cobrar) y un ingreso en el momento en que se emite la liquidación del impuesto, y no solo cuando el contribuyente realiza el pago."""),
        ("2.3. Definición y Propósito del Catastro", 2, """Sin embargo, para aplicar correctamente el devengado, es imprescindible contar con una base de datos catastral íntegra y precisa. El Catastro se define como el inventario o censo, debidamente actualizado y clasificado, de los bienes inmuebles pertenecientes al Estado y a los particulares. Este inventario tiene un propósito múltiple: físico (identificar los límites territoriales), jurídico (vincular el inmueble con su propietario) y económico (establecer el valor fiscal base para la tributación)."""),
        ("2.4. Marco Legal y Autonomía Municipal en Paraguay", 2, """En Paraguay, la Ley N° 3966/10 "Orgánica Municipal" otorga a las intendencias la autonomía política, administrativa y normativa para la gestión de sus intereses. El Artículo 169 de dicha ley establece que el Impuesto Inmobiliario es de competencia exclusiva de los municipios. No obstante, la legislación también obliga a las comunas a transferir el 15% de lo recaudado a las Gobernaciones Departamentales y otro 15% al Ministerio de Hacienda. Por tanto, una liquidación inexacta por fallas en el catastro no solo perjudica las arcas de Asunción, sino que constituye un incumplimiento de las obligaciones de transferencia a nivel nacional."""),
        ("2.5. Modernización Tecnológica", 2, """Autores contemporáneos en gestión pública coinciden en que la modernización de los sistemas catastrales es la inversión con mayor tasa de retorno para un municipio. Un catastro digitalizado, integrado con sistemas de información geográfica (SIG) y conectado en tiempo real con el módulo de tesorería, elimina la posibilidad de evasión fiscal por manipulación manual de datos. La doctrina sostiene que la descentralización fiscal, para ser efectiva, requiere instituciones locales con capacidad tecnológica para administrar bases de datos masivas."""),'''

    content = content.replace(old_cap2, new_cap2)

    old_cap3 = '''        ("CAPÍTULO 3. METODOLOGÍA", 1, """El presente trabajo de investigación se inscribe dentro de un enfoque cualitativo. Según Hernández Sampieri, Fernández y Baptista (2014), la investigación cualitativa busca comprender los fenómenos en su ambiente natural, extrayendo significado de los datos y enfocándose en la profundidad de la interpretación más que en la generalización estadística. En este caso, el objeto de estudio es el entramado administrativo y contable de la Municipalidad de Asunción.

El diseño de la investigación es no experimental, de tipo transeccional y descriptivo. Es no experimental puesto que no se han manipulado variables de forma deliberada; la recolección de datos se ha limitado a observar el fenómeno tal cual se presenta en el entorno de la Dirección de Catastro. Es descriptivo porque tiene como finalidad detallar los procesos, deficiencias y características del ciclo de recaudación del Impuesto Inmobiliario.

Como unidad de análisis se ha tomado el proceso de liquidación y registro contable ejecutado en el Departamento de Catastro en conexión con la Dirección de Administración y Finanzas. La recolección de datos se sustentó primordialmente en el análisis documental. Se revisaron manuales de funciones vigentes, memorias institucionales, reportes de auditoría interna y publicaciones de los principales medios de prensa nacionales que evidencian la magnitud del problema en la opinión pública.

El procedimiento de análisis de la información consistió en una revisión temática y triangulación de las normativas legales (Ley Orgánica Municipal) con los procedimientos descritos en los manuales internos, contrastándolos finalmente con los hallazgos reportados tanto por entes de control como por la prensa. Este cruce de información permitió garantizar el rigor y la objetividad de los resultados, minimizando posibles sesgos interpretativos."""),'''

    new_cap3 = '''        ("CAPÍTULO 3. METODOLOGÍA", 1, ""),
        ("3.1. Enfoque de Investigación", 2, """El presente trabajo de investigación se inscribe dentro de un enfoque cualitativo. Según Hernández Sampieri, Fernández y Baptista (2014), la investigación cualitativa busca comprender los fenómenos en su ambiente natural, extrayendo significado de los datos y enfocándose en la profundidad de la interpretación más que en la generalización estadística. En este caso, el objeto de estudio es el entramado administrativo y contable de la Municipalidad de Asunción."""),
        ("3.2. Diseño de la Investigación", 2, """El diseño de la investigación es no experimental, de tipo transeccional y descriptivo. Es no experimental puesto que no se han manipulado variables de forma deliberada; la recolección de datos se ha limitado a observar el fenómeno tal cual se presenta en el entorno de la Dirección de Catastro. Es descriptivo porque tiene como finalidad detallar los procesos, deficiencias y características del ciclo de recaudación del Impuesto Inmobiliario."""),
        ("3.3. Unidad de Análisis y Recolección de Datos", 2, """Como unidad de análisis se ha tomado el proceso de liquidación y registro contable ejecutado en el Departamento de Catastro en conexión con la Dirección de Administración y Finanzas. La recolección de datos se sustentó primordialmente en el análisis documental. Se revisaron manuales de funciones vigentes, memorias institucionales, reportes de auditoría interna y publicaciones de los principales medios de prensa nacionales que evidencian la magnitud del problema en la opinión pública."""),
        ("3.4. Procedimiento de Análisis", 2, """El procedimiento de análisis de la información consistió en una revisión temática y triangulación de las normativas legales (Ley Orgánica Municipal) con los procedimientos descritos en los manuales internos, contrastándolos finalmente con los hallazgos reportados tanto por entes de control como por la prensa. Este cruce de información permitió garantizar el rigor y la objetividad de los resultados, minimizando posibles sesgos interpretativos."""),'''

    content = content.replace(old_cap3, new_cap3)

    old_cap4 = '''        ("CAPÍTULO 4. RESULTADOS", 1, """La evaluación del ciclo de gestión del Impuesto Inmobiliario arrojó resultados que confirman las debilidades estructurales planteadas inicialmente. En primer lugar, se evidenció que la base de datos catastral opera en un entorno de software heredado (legacy system) que carece de una interfaz de programación de aplicaciones (API) para conectarse con el sistema de tesorería. Como consecuencia, las actualizaciones de titularidad y valuación fiscal deben procesarse mediante exportaciones manuales periódicas, con un margen de retraso de hasta 45 días.

La morosidad calculada sobre la base de los reportes internos disponibles asciende a niveles críticos. Se identificó que existe una gran cantidad de expedientes con solicitudes de actualización o reclamos por facturación doble que no han sido procesados. La prensa ha corroborado esta situación, indicando que el desorden administrativo ha llevado a que numerosos contribuyentes opten por la morosidad a la espera de "perdonazos" fiscales o prescripciones legales de sus deudas, lo cual erosiona gravemente la cultura tributaria de la capital.

Asimismo, la revisión de los manuales de procedimientos demostró que no existen controles cruzados automatizados para validar las liquidaciones diarias. El personal responsable debe validar visualmente las partidas, lo cual incrementa el riesgo de error humano a niveles inaceptables para una administración de esta escala. En términos contables, esto significa que los balances financieros presentados por el municipio podrían estar sobrevalorando significativamente la cuenta de "Deudores por Impuestos", ya que incluyen partidas que, por errores del propio catastro, no son exigibles jurídicamente."""),'''

    new_cap4 = '''        ("CAPÍTULO 4. RESULTADOS", 1, ""),
        ("4.1. Debilidades Estructurales del Catastro", 2, """La evaluación del ciclo de gestión del Impuesto Inmobiliario arrojó resultados que confirman las debilidades estructurales planteadas inicialmente. En primer lugar, se evidenció que la base de datos catastral opera en un entorno de software heredado (legacy system) que carece de una interfaz de programación de aplicaciones (API) para conectarse con el sistema de tesorería. Como consecuencia, las actualizaciones de titularidad y valuación fiscal deben procesarse mediante exportaciones manuales periódicas, con un margen de retraso de hasta 45 días."""),
        ("4.2. Análisis de Morosidad", 2, """La morosidad calculada sobre la base de los reportes internos disponibles asciende a niveles críticos. Se identificó que existe una gran cantidad de expedientes con solicitudes de actualización o reclamos por facturación doble que no han sido procesados. La prensa ha corroborado esta situación, indicando que el desorden administrativo ha llevado a que numerosos contribuyentes opten por la morosidad a la espera de "perdonazos" fiscales o prescripciones legales de sus deudas, lo cual erosiona gravemente la cultura tributaria de la capital."""),
        ("4.3. Falta de Controles y Riesgo Contable", 2, """Asimismo, la revisión de los manuales de procedimientos demostró que no existen controles cruzados automatizados para validar las liquidaciones diarias. El personal responsable debe validar visualmente las partidas, lo cual incrementa el riesgo de error humano a niveles inaceptables para una administración de esta escala. En términos contables, esto significa que los balances financieros presentados por el municipio podrían estar sobrevalorando significativamente la cuenta de "Deudores por Impuestos", ya que incluyen partidas que, por errores del propio catastro, no son exigibles jurídicamente."""),'''

    content = content.replace(old_cap4, new_cap4)

    old_cap5 = '''        ("CAPÍTULO 5. ANÁLISIS Y DIAGNÓSTICO", 1, """El análisis de los resultados a la luz del marco normativo revela una brecha considerable entre el deber ser jurídico y la praxis administrativa. La falta de un catastro depurado y conectado al sistema financiero contraviene el principio fundamental de fiabilidad de la información contable. La Municipalidad de Asunción, al basar sus estados financieros en datos parcialmente inexactos, se expone a observaciones severas por parte de la Contraloría General de la República.

El diagnóstico situacional indica que el problema no es meramente técnico, sino de diseño organizacional. La Dirección de Catastro y la Dirección de Recaudaciones operan como silos estancos, compartiendo información solo cuando existen coyunturas de cierre fiscal. Esta cultura de aislamiento departamental es la verdadera causa raíz de las duplicaciones de obligaciones y de los cobros indebidos reportados por los contribuyentes.

A nivel internacional, estudios recientes del Banco Interamericano de Desarrollo (BID, 2021) sobre gestión catastral en América Latina enfatizan que la interoperabilidad entre catastro y finanzas es el pilar de la autonomía municipal. Asimismo, la Comisión Económica para América Latina y el Caribe (CEPAL, 2020) señala que los municipios con sistemas aislados pierden en promedio un 35% de su potencial recaudatorio por "fugas de información". Al comparar la realidad de Asunción con estos estándares internacionales, es evidente que el municipio se encuentra en un estadio de rezago tecnológico que imposibilita la implementación de políticas tributarias progresivas y justas.

Si bien las intenciones de implementar "listas negras" o tercerizar el cobro demuestran un interés por aumentar la recaudación, aplicar estas medidas punitivas sobre una base de datos defectuosa es un error estratégico de alto riesgo legal. La institución enfrenta posibles demandas colectivas por daños y perjuicios si procede al embargo o reporte negativo de contribuyentes cuyos pagos no han sido registrados por fallas internas. La modernización debe empezar desde el núcleo de los datos (core data) antes de avanzar hacia herramientas coercitivas."""),'''

    new_cap5 = '''        ("CAPÍTULO 5. ANÁLISIS Y DIAGNÓSTICO", 1, ""),
        ("5.1. Brecha entre Normativa y Praxis Administrativa", 2, """El análisis de los resultados a la luz del marco normativo revela una brecha considerable entre el deber ser jurídico y la praxis administrativa. La falta de un catastro depurado y conectado al sistema financiero contraviene el principio fundamental de fiabilidad de la información contable. La Municipalidad de Asunción, al basar sus estados financieros en datos parcialmente inexactos, se expone a observaciones severas por parte de la Contraloría General de la República."""),
        ("5.2. Aislamiento Organizacional", 2, """El diagnóstico situacional indica que el problema no es meramente técnico, sino de diseño organizacional. La Dirección de Catastro y la Dirección de Recaudaciones operan como silos estancos, compartiendo información solo cuando existen coyunturas de cierre fiscal. Esta cultura de aislamiento departamental es la verdadera causa raíz de las duplicaciones de obligaciones y de los cobros indebidos reportados por los contribuyentes."""),
        ("5.3. Estándares Internacionales vs Realidad Local", 2, """A nivel internacional, estudios recientes del Banco Interamericano de Desarrollo (BID, 2021) sobre gestión catastral en América Latina enfatizan que la interoperabilidad entre catastro y finanzas es el pilar de la autonomía municipal. Asimismo, la Comisión Económica para América Latina y el Caribe (CEPAL, 2020) señala que los municipios con sistemas aislados pierden en promedio un 35% de su potencial recaudatorio por "fugas de información". Al comparar la realidad de Asunción con estos estándares internacionales, es evidente que el municipio se encuentra en un estadio de rezago tecnológico que imposibilita la implementación de políticas tributarias progresivas y justas."""),
        ("5.4. Riesgos Legales por Base de Datos Defectuosa", 2, """Si bien las intenciones de implementar "listas negras" o tercerizar el cobro demuestran un interés por aumentar la recaudación, aplicar estas medidas punitivas sobre una base de datos defectuosa es un error estratégico de alto riesgo legal. La institución enfrenta posibles demandas colectivas por daños y perjuicios si procede al embargo o reporte negativo de contribuyentes cuyos pagos no han sido registrados por fallas internas. La modernización debe empezar desde el núcleo de los datos (core data) antes de avanzar hacia herramientas coercitivas."""),'''

    content = content.replace(old_cap5, new_cap5)

    old_cap6 = '''        ("CAPÍTULO 6. PROPUESTAS Y RECOMENDACIONES", 1, """Con base en el diagnóstico, se formulan las siguientes recomendaciones para la optimización de la gestión contable vinculada al catastro:

1. Desarrollo e Implementación de un Sistema Integrado de Información Municipal (SIIM): Es imperativa la migración de los datos del catastro a una base de datos relacional moderna que se comunique en tiempo real (web services) con el módulo contable. Esta integración eliminará la intervención manual en la liquidación del impuesto y garantizará que los pagos realizados se reflejen inmediatamente en la cuenta corriente del contribuyente.

2. Auditoría y Depuración Masiva del Padrón Catastral: Previo a cualquier acción de cobro coercitivo, se recomienda ejecutar un proyecto de actualización de datos, cruzando información con la Dirección General de los Registros Públicos y el Servicio Nacional de Catastro, para sanear las duplicaciones y errores de titularidad identificados en los resultados.

3. Actualización de Normativas y Manuales Internos: Redactar un nuevo Manual de Procedimientos para la Gestión del Impuesto Inmobiliario que establezca protocolos estrictos de conciliación diaria de ingresos y delineé las responsabilidades específicas de los funcionarios en cada etapa del ciclo tributario."""),'''

    new_cap6 = '''        ("CAPÍTULO 6. PROPUESTAS Y RECOMENDACIONES", 1, "Con base en el diagnóstico, se formulan las siguientes recomendaciones para la optimización de la gestión contable vinculada al catastro:"),
        ("6.1. Sistema Integrado de Información Municipal (SIIM)", 2, """1. Desarrollo e Implementación de un Sistema Integrado de Información Municipal (SIIM): Es imperativa la migración de los datos del catastro a una base de datos relacional moderna que se comunique en tiempo real (web services) con el módulo contable. Esta integración eliminará la intervención manual en la liquidación del impuesto y garantizará que los pagos realizados se reflejen inmediatamente en la cuenta corriente del contribuyente."""),
        ("6.2. Auditoría y Depuración Masiva", 2, """2. Auditoría y Depuración Masiva del Padrón Catastral: Previo a cualquier acción de cobro coercitivo, se recomienda ejecutar un proyecto de actualización de datos, cruzando información con la Dirección General de los Registros Públicos y el Servicio Nacional de Catastro, para sanear las duplicaciones y errores de titularidad identificados en los resultados."""),
        ("6.3. Actualización Normativa", 2, """3. Actualización de Normativas y Manuales Internos: Redactar un nuevo Manual de Procedimientos para la Gestión del Impuesto Inmobiliario que establezca protocolos estrictos de conciliación diaria de ingresos y delineé las responsabilidades específicas de los funcionarios en cada etapa del ciclo tributario."""),'''

    content = content.replace(old_cap6, new_cap6)

    with open('generate_final_clean.py', 'w', encoding='utf-8') as f:
        f.write(content)

update_christhian()
